### ISSUE TITLE
logout timer issue

### ISSUE THREAD

**Issue by JiejayLan** [JiejayLan/CSC336_group_project#14]
I add a logout timer to the index.js page.It will load the logoutTimer function if there is an session.user.id!=undefined But it looks like it is not a very smart way by hard coding the timer function. If anyone find a better way, please improve it.

**Comment by shiBinH** [comment]
For now let's only allow the user to logout by using the logout button?

**Comment by JiejayLan** [comment]
np, I will comment out the timer part

**Comment by shiBinH** [comment]
I will look into a way of removing session data after a certain period of time.

**Comment by JiejayLan** [comment]
Well, this is not that important, we can come back to this problem if we have time.
