### ISSUE TITLE
add one more Collaborators

### ISSUE THREAD

**Issue by JiejayLan** [JiejayLan/CSC336_group_project#15]
shibin is really good at web development, I am going to add him as an extra Collaborators. He can do the merge without my permission. The other reason is that I need to prepare to my exam next week, can't contribute more time into this project.

**Comment by shiBinH** [comment]
Thanks for the compliment, and sure, I will help out with the merging.

**Comment by JiejayLan** [comment]
https://github.com/JiejayLan/CSC336_group_project/invitations here is ur invitation link
