### ISSUE TITLE
 check if employee or employer

### ISSUE THREAD

**Issue by JiejayLan** [JiejayLan/CSC336_group_project#17]
In the authenticate.js it should also check the user_type table to see if this is a employee or employer. Aslo, store the user_type into the request.session.user. Because, not all user can submit a job application or post a new job.

**Comment by shiBinH** [comment]
Working on it right now. I will test the new query once our database is back up.

**Comment by shiBinH** [comment]
From _init_datababse.sql_ it seems that the entries for the _User_Type_ relation store a user's ID and a string containing the employee type. The relation should be _User_Type (type_ID, type_name)_ in which _type_ID_ is a primary key. Currently only two entries should be in the relation: employee type and employer type. The User relation should contain a _Employee_Type_ field that references the _type_ID_ in the _User_Type_ relation.

@Hongzred @JiejayLan

**Comment by JiejayLan** [comment]
Sorry, I don't get your point. Can you code it down?

**Comment by shiBinH** [comment]
The _User_ relation should look like this

_User(user_ID..., user_type)_

and some entries would be 

_('Shi Bin', ..., 1), ('Jie Lan', ..., 1), ('Gong', ..., '2'), ('Hong', ..., '2)_

The user type relation should be _User_Type(**type_id**, type_name)_. The entries would probably be

_(1, 'Employee'), (2, 'Employer')_

This way the type names are not repeated for every user, and if we have to change anything  about a user type we would only have to change the user type entry in the relation. The current separation is somewhat pointless. We might as well have just added the type name as an attribute to _User_.

**Comment by JiejayLan** [comment]
I see. I will update it this afternoon.

**Comment by JiejayLan** [comment]
The init_datababse.sql has been update, so does the online rds
