### ISSUE TITLE
natural join in authenticate

### ISSUE THREAD

**Issue by JiejayLan** [JiejayLan/CSC336_group_project#22]
I think there might be a error in your QUERY in the authenticate.js.
You use natural join here, and it return (if i login with shi bin, shibin)
[ RowDataPacket {
    user_ID: 100,
    username: 'shi bin',
    password: 'shibin',
    phone_number: '547-502-5653',
    email: 'shibin32@gmail.com',
    user_type: 1,
    type_ID: 1,
    type_name: 'employee' },
  RowDataPacket {
    user_ID: 100,
    username: 'shi bin',
    password: 'shibin',
    phone_number: '547-502-5653',
    email: 'shibin32@gmail.com',
    user_type: 1,
    type_ID: 2,
    type_name: 'employee' } ]

The problem here, because natural join only take care of two tables have common attribute name. But not in our case, so it will return a Cartesian product of two tables.

**Comment by JiejayLan** [comment]
https://www.w3resource.com/sql/joins/using-a-where-cluase-to-join-two-tables-related-by-a-single-column-primary-key-or-foriegn-key-pair.php
I think this is a good example to join two tables with a pair of foreign key

**Comment by shiBinH** [comment]
Yes seems like the query returns a product. I will update it to
```MySQL
SELECT
    *
FROM
    USER, USER_TYPE
WHERE
    User.username=username AND
    User.password=password AND
    User_Type.type_ID=User.user_type
;
```
