### ISSUE TITLE
auto logout issue

### ISSUE THREAD

**Issue by JiejayLan** [JiejayLan/CSC336_group_project#32]
I saw how you finish that part with SESSION_EXPIRED. That is an very interesting way. But looks like there is still some security problems.(I didn't run your code, hope I dont misunderstand)

1. If you stay at the same page for 2 minutes, even you still be active(has mouse and keyboard event), when you go to different page, it will logout.
2.If you login the profile page and forget to logout, the next person come to your computer still can see all the information on that page. Of course he can't check different page bu using your account.

I will say no need to change not. I just post this for further discussion and study.

**Comment by shiBinH** [comment]
In general I think our application is not very secure with regards to the handling of user credentials. However, as the primary goal of the this project is to "interact with the database in a nontrivial way", for now the current implementation of sessions should do. And regarding your the issues you brought up:

1. Yes I believe that is the current behavior: the user will be logged out if he has not refreshed the page for a given time. I implemented the session logic mainly to prevent indefinite storage of user data on  `req.session`. If I am correct, the only way to remove user data from `req.session` prior to this commit was to either manually logout or restart the server. But I agree that the expiration countdown of a session should not begin if the user continues to browse the same page. I can imagine a possible solution is to check if the user is active and, if so, periodically send an asynchronous request (using AJAX [https://en.wikipedia.org/wiki/Ajax_(programming)](url)) to the server to refresh user sessions.

2. I think you're suggesting that, to protect sensitive information, the user should be automatically logged out and redirected to another page after a certain period of inactivity. We can likely tackle this issue using a similar approach to what I suggested above: check for inactivity and then redirect the user.

**Comment by JiejayLan** [comment]
Thank you for your explanation. I post this issue only for discussion. We can focus on other projects now. On next meeting, we can discuss about more features.
