### ISSUE TITLE
'/:id' endpoint overshadowing other endpoints

### ISSUE THREAD

**Issue by shiBinH** [JiejayLan/CSC336_group_project#9]
The endpoint at
`app.get('/:id', require('./controllers/jobs_controller.js')(CONNECTION));`
in _server.js_ catches all other endpoints of the form _/\<anything\>_, like _/login_, _/register_, etc. I think renaming the endpoint (perhaps to _/jobs/:userId_?) will fix this problem, or else the handlers of other endpoints that it unintentionally catches have to be moved before the handler of the _'/:id'_.
@JiejayLan

**Comment by JiejayLan** [comment]
Yes, I aware this problem, I will change the endpoint
